apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-manager
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.discord: ""
    notifications.argoproj.io/subscribe.on-sync-failed.discord: ""
    notifications.argoproj.io/subscribe.on-health-degraded.discord: ""
spec:
  project: default

  source:
    repoURL: https://github.com/<YOUR_USERNAME>/devops-task-manager.git
    targetRevision: main
    path: k8s/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: task-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
