---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    discord-webhook-url: AgBt4QwJyG+RklKNE4RQjSO9kNpEuKUYhZJEmH+CLMU7yck08uLyZctrBFVC5Yrp08GczIzM8cOSm2sTlozpT+smtye14G+rMUaR370ysJY5gM60ApyTg7IP+tR39GkqSVFQRrZmkhcB/r868N5iDnO+uYzWHU8wfjDtpdwKIOTnAJXv8riTrXhTjSiQHw0guaSQVkHLaxdHE/mQe9FxuuNug9KuOCb+xQwm344wxOQF9oGpUzVtzu/ShYGClyLTs3luG42AjGFUEh0iRX/HIsBx/dSUP2s3LGETDcB/97OJhnL3ynTuz+ACWXS873+kCJVZQEn7Wf5yTmthIYYkxcjw4eXAZpjm8Dc0P45QYqIlGOfUdUk9cqwTjiuXj7dteKyYzwSjR/7R6D4AC64mqVvu4x/HDkhlh8iONdh1NutYxh0qOlf/a94iMjIevfy/WtRTJd1Dbp5g6MIyQlIG/uleHGrhLki4+KXaWp6Tnr9C/f6uOtEyaNC15wBlN4F9y9S9Ealogjeb/rLRgBZltauLtuCbykT3mZJchRgGR4lRMo4/yegaRTO9GRx+uEDWPLvC0Rw3X1MO8Ns3Gxfr6c6acrhQXJRn2Q8wr/OP92LLp90LTr20X+DKQTseZH81/VXSJ4tDl1yIws/GWZfn88vWn9a5xLhe61rEKX1XVP6PpT2SEYSmut99WZcFlW7/6ftCPXBO/EwZoTz/qL9Yrfebs87B+Q6dEbt94/79oVAwWpWNs7QUSDnkNYN/+wm0RC1YPQq4PJuGTzIUbxxOlKXvfPVNDb6LEHpYGcRLL6GPZ54mJ7IY7stPdlEyJvG4M8hGE7NSZQ6Lsw4r7p1Z6LqjCC3183nXMD2w
  template:
    metadata:
      creationTimestamp: null
      name: argocd-notifications-secret
      namespace: argocd
