apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-manager

resources:
  - namespace.yaml
  - configmap.yaml
  - sealed-secret.yaml
  - postgres-statefulset.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: task-manager
  app.kubernetes.io/managed-by: kustomize
