---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: task-manager-db-secret
  namespace: task-manager
spec:
  encryptedData:
    DATABASE_PASSWORD: AgAObMgFCkXLsyAYF2lInW5mJD7oXexSa0A96/UJ0mC8YMAio8EJTukWjGyOhiZygi++e6V0m2QG8RH6LKAERo/xNWm/DNbjcEDoMbQ680JjVsqJzPIC2djM2vPtY80DiCSVIVuEUr7gyTr2j8CpzhP7Q/tbHJGEmIQtcldVb0ZGQB1I/ajTl/OWRTOhmHanDynXg/0UgdNlpv9ZMqRVrJMFNX6aTOJTpEE+0Xp7JJHDqefuZeKXdD0shzoPOLrMi3tNK7NT7QFX9Ej1le5ICKC1gOzuDyblRzbhiuNS7O4dwv5ptYYewpCcMVUQJk2XbYwGYcHB+zzsg+z81dhHeb0gpa7mcLL/XGMNihRN3k9KxdmKfcNDDVrtUYYxaj9ZRDUY+xQSh2fKcybvPWUOvmoYljOHyYnngXKJZ5/NurZs3tiAoCf8/irarf30FYg9czpqw0eUrba945ma0CF2LesY54OwjW0dcFdtHD1qMG1/DaAkMUWs+ib6QB/iNFMNJvYww8DsC50yr4SDOw2xM4ea7XVEWEhq9z2k1o2kWfn3oa6bqgxHKV5N3D85SV3wQj0CkAaM4whgxdIFnoZJ7juocKPZuYufC8DjfStToQLNVruBcOhQOEs86zyZKXjpx8Ufe9JEd2CQ9JCNEHI+h0AUZu5zm9B6GMd+8rVLBo097dxpC2+DSDE3B7WPXiDFH3kVoLXSWKRAxcssgfdnv7j7PkrtnlpUg5A=
  template:
    metadata:
      creationTimestamp: null
      name: task-manager-db-secret
      namespace: task-manager
